### ISSUE TITLE
Obtaining the End Effector external forces through FRI

### ISSUE THREAD

**Issue by TheCamusean** [RobotLocomotion/drake-iiwa-driver#29]
Hi,

I am not sure if you have dealed with this problem, but as far as I found, I have not been able to obtain the external end effector Force directly from the robot using the FRI communication.

Have you solved the problem in any way? Or you are applying Jacobian to obtain it in PC side?

Thanks!!

**Comment by sammy-tri** [comment]
We're calculating this on the PC side based on the joint torques.  I believe you are correct that this is not directly available from the robot (it definitely isn't in joint control mode, and I haven't personally used the cartesian control mode so I don't know what's available there).

**Comment by sammy-tri** [comment]
Closing as no further action is planned to calculate the external forces in this driver.
