### ISSUE TITLE
Unexpected violent jerk during motion

### ISSUE THREAD

**Issue by y8han** [RobotLocomotion/drake-iiwa-driver#38]
Hi, when I was running kuka_driver.cc and send the goal pose info via lcm, the robot arm (**Kuka IIWA**) may sometimes return to zero position in a violent jerk. After I went deep into codes, it seems to me that the reason is something wrong with the fri communication. I saw a flag (restart_fri) and if I set it to be true, the robot will first return to zero position in a jerk and then come back in another jerk...
Does someone observe the same thing happens? Is it possible that we solve the fri communication issue, or at least when it breaks, the robot arm keeps still?
Thanks in advance for any suggestions.

**Comment by y8han** [comment]
Hi, I think when I was manipulating the robot arm, there was indeed only one PC sending IIWA_COMMAND. Also, I prined out the message on terminal when this happened:
**_Re-entering command state.
Holding position and ignoring LCM commands._**
Do you have any ideas? Thanks in advance.

**Comment by sammy-tri** [comment]
So, it sounds like the move to zero positions is associated with the FRI link to the robot having issues (and then recovering).  I'd recommend not using `--restart_fri` (which it looks like you weren't in this most recent report) as it sounds like that causes the robot to go back to the old position (after zeroing!), which is probably even worse.

Here are some ideas we can try to attempt to narrow things down...

* Can you post more of the terminal output?  There should probably be (among other things) some lines starting with `onStateChange` before (and maybe after) the `Re-entering command state.` output.

* Can you try to capture an LCM log of the robot control/status messages so we can see what the driver is actually reporting?  I think running something like `lcm-logger -c IIWA.\*` should only capture the robot messages and not produce too large of a log. 

* Once the driver prints `Holding position and ignoring LCM commands` it's supposed to keep sending commands for whatever the current position of the robot is over FRI (and, like it says, ignore LCM commands).  It's possible that this isn't working correctly?  We could try modifying the driver to stop the program (like call `exit` or something) after the message is printed at https://github.com/RobotLocomotion/drake-iiwa-driver/blob/master/kuka-driver/kuka_driver.cc#L505` 

I'll let you know if I think of anything else.

**Comment by sammy-tri** [comment]
`joint_position_when_command_entered_` is updated whenever the robot enters the `COMMANDING_ACTIVE` state, not just the first time.  https://github.com/RobotLocomotion/drake-iiwa-driver/blob/master/kuka-driver/kuka_driver.cc#L485

If the driver is exiting inside of `onStateChange`, then I would expect that `command` is never called, and so the driver shouldn't have a chance to command anything to the robot over FRI at all, so I'm not sure where the motion is coming from (maybe `command` is being called anyway?  But the position still shouldn't be zeros).  I don't know why we would call `setJointPosition` https://github.com/RobotLocomotion/drake-iiwa-driver/blob/master/kuka-driver/kuka_driver.cc#L561 with the zero position, and I don't know why the robot would move to zero if we didn't.  Maybe add a check at the call to `setJointPosition` to print (or exit?) if it's ever called with zeros?

LCM logs would probably help.

What version of the Sunrise FRI package are you using?  And what software version is running on the robot?  What Java application is running on the robot?  (I'm guessing `sunrise_1.11/DrakeFRITorqueDriver.java` from drake-iiwa-driver?)

**Comment by y8han** [comment]
Hi Sammy,
We found that the issue may be caused by the robot hardware issues (maybe the communication drive inside the robot arm).
The programming codes are good and we tested it on the other Kuka IIWA arm and there was no weird zeroing.
Sorry for bothering you and I really appreciate your efforts on building this reliable tools for the community.

**Comment by sammy-tri** [comment]
Glad to hear it's working for you now.

**Comment by y8han** [comment]
Hi Sam,
Thank you for your help! Indeed, I have a new comment for another issue and
it has been added on Github.
Best,
Yunhai
